/**:
  ros__parameters:
    keep_last_trajectory_s: 0.5 # [s]
    nearest_dist_threshold_m: 1.5 # [m]
    nearest_yaw_threshold_rad: 1.0 # [rad]
    target_pull_out_speed_mps: 1.0 # [mps]
    target_pull_out_acc_mps2: 1.0 # [mps2]
    max_speed_mps: 5.0 #[5 kmph], 2.77[10 kmph], 4.16[15 kmph] [mps]
    max_lateral_accel_mps2: 1.5 #[mps2]
    spline_interpolation_resolution_m: 0.5 # [m]
    backward_trajectory_extension_m: 5.0 # [m]
    use_akima_spline_interpolation: true
    smooth_trajectories: true
    limit_speed: true
    limit_lateral_acceleration: true
    set_engage_speed: false
    fix_invalid_points: true
    smooth_velocities: false
    publish_last_trajectory: false
    keep_last_trajectory: false
    extend_trajectory_backward: true
    
    # Plugin execution sequence
    # Defines the order and configuration of optimization plugins
    # Format: comma-separated list of plugin names with optional modifiers
    # Available plugins: trajectory_extender, trajectory_point_fixer, eb_smoother, spline_smoother, velocity_optimizer
    # Default sequence matches the original hardcoded behavior
    plugin_execution_sequence: "trajectory_extender,trajectory_point_fixer,eb_smoother,spline_smoother,velocity_optimizer,spline_smoother,trajectory_point_fixer"
